name       : corebird
version    : 1.2
release    : 5
source     :
    - https://github.com/baedert/corebird/archive/1.2.tar.gz : b495f2232569a605cf3fd9c8ebc87633ba9645fb5b0a3ec00ac95736dbb15a9c
license    : GPL-3.0
summary    : Native Gtk+ Twitter Client
description: |
    Native Gtk+ Twitter Client
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(gdk-x11-3.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(gstreamer-video-1.0)
    - vala
    - glib-networking
setup      : |
    ./autogen.sh --prefix=/usr
build      : |
    %make
install    : |
    %make_install
