name       : corebird
version    : 1.2.2
release    : 7
source     :
    - https://github.com/baedert/corebird/archive/1.2.2.tar.gz : b3d6a9f2e9fcb17acbd1e91159302398d18877f16101612da5a55886f7add752
license    : GPL-3.0
summary    : Native Gtk+ Twitter Client
description: |
    Native Gtk+ Twitter Client
component  : network.clients
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(gdk-x11-3.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(gstreamer-video-1.0)
    - vala
    - glib-networking
setup      : |
    %autogen --prefix=/usr
build      : |
    %make
install    : |
    %make_install
