name       : corebird
version    : 1.3.1
release    : 8
source     :
    - https://github.com/baedert/corebird/archive/1.3.1.tar.gz : cbc832b9e3adab698b9b879b64e33bffd708776e08fe9f229885068193525190
license    : GPL-3.0
summary    : Native Gtk+ Twitter Client
description: |
    Native Gtk+ Twitter Client
component  : network.clients
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(gdk-x11-3.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(gstreamer-video-1.0)
    - vala
    - glib-networking
setup      : |
    %autogen --prefix=/usr
build      : |
    %make
install    : |
    %make_install
