name       : corebird
version    : 1.3.2
release    : 9
source     :
    - https://github.com/baedert/corebird/archive/1.3.2.tar.gz : ead9c00171a0cfed4ad9d33a5136e465d6ea6cd12b3c509e2ca323ed0b18eca9
license    : GPL-3.0
summary    : Native Gtk+ Twitter Client
description: |
    Native Gtk+ Twitter Client
component  : network.clients
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(gdk-x11-3.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(gstreamer-video-1.0)
    - vala
    - glib-networking
setup      : |
    %autogen --prefix=/usr
build      : |
    %make
install    : |
    %make_install
