name       : corebird
version    : 1.0
release    : 1
source     :
    - https://github.com/baedert/corebird/archive/1.0.tar.gz : 0ca4ca20b0281b2901382810ef8bd1682bb896c3915ad3bea3f2a41461118001
license    : GPL-3.0
summary    : Native Gtk+ Twitter Client
description: |
    Native Gtk+ Twitter Client
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(gdk-x11-3.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(gstreamer-video-1.0)
    - vala
    - glib-networking
setup      : |
    ./autogen.sh --prefix=/usr
build      : |
    %make
install    : |
    %make_install