name       : corebird
version    : 1.2.1
release    : 6
source     :
    - https://github.com/baedert/corebird/archive/1.2.1.tar.gz : 880c811ae00b2a88a7a3cf37fb1f0168e0aca241517a512babda39a30a8db5bd
license    : GPL-3.0
summary    : Native Gtk+ Twitter Client
description: |
    Native Gtk+ Twitter Client
component  : network.clients
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(gdk-x11-3.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(gstreamer-video-1.0)
    - vala
    - glib-networking
setup      : |
    ./autogen.sh --prefix=/usr
build      : |
    %make
install    : |
    %make_install
