name       : corebird
version    : 1.4.2
release    : 12
source     :
    - https://github.com/baedert/corebird/archive/1.4.2.tar.gz : 776ff02e6b58b9d2019b141047eccf25615e3ac50a2092c665e15dabf4ec8e1f
license    : GPL-3.0
summary    : Native Gtk+ Twitter Client
description: |
    Native Gtk+ Twitter Client
component  : network.clients
builddeps  :
    - pkgconfig(gdk-x11-3.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gspell-1)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - glib-networking
    - vala
setup      : |
    %autogen --prefix=/usr
build      : |
    %make
install    : |
    %make_install
